### ISSUE TITLE
Allow etcd to run in --proxy mode

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/etcd-release#19]
https://coreos.com/etcd/docs/latest/proxy.html

This will allow etcd proxy to be run on all jobs/vms, and allow clients to talk only to their singular local proxy and not need to manage the single or multiple connections to etcd servers. Consul has this with consul agent mode and its a wonderful pattern.

**Comment by Amit-PivotalLabs** [comment]
Thanks @drnic, I didn't know about that feature of etcd! There are several drawbacks to Consul's agent pattern, but mostly around the fact that you essentially *have to* follow that pattern.  I think etcd's proxy pattern is nicer, since it's optional -- colocate the proxy if it makes sense for you, talk directly to the server if that makes sense instead.

While this might be nice to have, we're a far ways from being able to add much in the way of new features to etcd-release right now.  A feature like this would require a heavy amount of system-level/acceptance-level testing as well.  I will close this issue for now, but we may reconsider it in the future.

Thanks again,
Amit

**Comment by drnic** [comment]
https://github.com/cloudfoundry-incubator/etcd-release/releases/tag/v56 Awesome!!
