### ISSUE TITLE
error in uploading etcd-release v117

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/etcd-release#44]
Blobstore error: sha1 mismatch expected=sha256:37e8b426f2dfda6b26f1044907f3ed0503f2ac91d693c484eda50abe3b18be86 actual=033e3a4cc8cd3c9e5a80c848adf4a7c0743004e4

**Comment by evanfarrar** [comment]
Hey @abhilash07 !

What version of the BOSH director and BOSH CLI are you running? We've begun signing our releases with SHA256, because of vulnerabilities in SHA1. You could also get non-sha256 signed releases via bosh.io:

https://bosh.io/releases/github.com/cloudfoundry-incubator/etcd-release?all=1

**Comment by genevievelesperance** [comment]
@abhilash07 have you been able to upload etcd-release with the latest bosh director and bosh-cli?

**Comment by abhilash07** [comment]
@genevievelesperance  you mean bosh-cli is bosh2 ??

**Comment by genevievelesperance** [comment]
@abhilash07 yes
