### ISSUE TITLE
Protips/tools for backup/restore

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/etcd-release#6]
Document any protips/tools/suggestions for backup/restore of etcd cluster. I think in the past we haven't cared about etcd as its only contained cached state for hm9000; perhaps as a general release it'd be helpful to document/enable this?

**Comment by drnic** [comment]
Offering `--wal-dir` to enable WAL might be a starting point; from reading https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md

**Comment by drnic** [comment]
https://coreos.com/etcd/docs/latest/admin_guide.html#restoring-a-backup

**Comment by Amit-PivotalLabs** [comment]
Hey @drnic 

This will likely require a fair bit of research, and we have a ways to go before we feel what we currently have has sufficiently robust testing.  This is an important thing to have on the roadmap for a data product like etcd, so thank you for bringing attention to this and the useful links.  In the near term, there is nothing actionable we can provide you.  Rather than having long-running inactive open issues, I will close this one, but I have repurposed the tracker story linked above by @cf-gitbot to serve as a placeholder for figuring out a proper backup and restore feature set.
